# Welcome to Jekyll!
title: Anders Emil Nielsen
email: aemilnielsen@gmail.com
description: On limecode.dk - Anders Emil Nielsen's personal website you will find his resume, github account and thoughts on some programming topics
baseurl: ""
url: "https://limecode.dk"
twitter_username: anderslimes
github_username:  anderslime

author:
  name: Anders Emil Nielsen

permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
highlighter: rouge
