# Welcome to Jekyll!
title: Anders Emil Nielsen
email: aemilnielsen@gmail.com
description: >
  This is just awesome
baseurl: ""
url: "https://limecode.dk"
twitter_username: anderslimes
github_username:  anderslime

author:
  name: Anders Emil Nielsen

# Build settings
markdown: kramdown
